# Generated by Django 2.1.5 on 2019-01-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COFFEE', 'coffee'), ('MILK', 'milk'), ('WATER', 'water')], help_text='Ingredient name', max_length=8)),
                ('amount_left', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Recipe name', max_length=64)),
                ('description', models.CharField(blank=True, help_text='Recipe description', max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
                'db_table': 'recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientsAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_amount', models.FloatField(help_text='Recipe ingredient required amount')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amount', to='coffiemachine.Ingredient')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_amount', to='coffiemachine.Recipe')),
            ],
            options={
                'verbose_name': 'recipe ingredient',
                'verbose_name_plural': 'recipe ingredients',
                'db_table': 'recipeingredients',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='user district role', related_name='recipes', through='coffiemachine.RecipeIngredientsAmount', to='coffiemachine.Ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredientsamount',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
